  # RETRIVING STUDENT TAKING  COURSE of course id 6
 SELECT COURSE.COURSE,STUDENT.NAME,COURSE_STUDENT.COURSE_ID,COURSE_STUDENT.STUDENT_ID FROM COURSE
						JOIN COURSE_STUDENT ON COURSE_STUDENT.COURSE_ID =COURSE.ID
                        JOIN STUDENT ON STUDENT.ID = COURSE_STUDENT.STUDENT_ID
                        WHERE COURSE.ID = 6; 
                        
      
      SELECT * FROM STUDENT;
      
      DESCRIBE STUDENT;
      

#DELETING ENTRY FROM STUDENT TABLE
DELETE FROM STUDENT WHERE ID=5;

#updating AN ENTRY IN COURSE TABLE 
UPDATE course SET PREREQUIESTS = 'INTERNET' 
      WHERE COURSE = 'HTML';# NOT WORKING BECAUSE OF SAFE MODE

SELECT * FROM course;

# MODIFYING DATATYPE OF AN COUMN PHONE
ALTER TABLE STUDENT MODIFY COLUMN PHONE INT(10);

DESCRIBE STUDENT;
SELECT * FROM STUDENT;

#UPDATEING STUDENT TABLE 
UPDATE STUDENT 
SET PHONE = '123456789'
WHERE NAME LIKE '%KSENIA%';#NOT WORKING BECAUSE OF SAFE MODE

UPDATE STUDENT SET ADDRESS = 'HOME'
WHERE ID=1;

UPDATE STUDENT SET ADDRESS = 'HOME' WHERE ID =3;
UPDATE STUDENT SET PHONE = '123456' WHERE ID = 4;

# ALTERING TABLE BY ADDING AND DROPPING COLUMN 'ADDRESS'
ALTER TABLE STUDENT ADD ADDRESS VARCHAR(255);
ALTER TABLE STUDENT DROP ADDRESS;

# ALTERING TABLE BY DROPPING AND ADDING COLUMN 'PHONE' WITH DEFAULT VALUE
ALTER TABLE STUDENT DROP PHONE;
ALTER TABLE STUDENT ADD PHONE VARCHAR(255) DEFAULT '11111';

#DROPPING COLUMN FROM COURSE
ALTER TABLE COURSE DROP END_DATE;

ALTER TABLE COURSE ADD TODAY YEAR;

ALTER TABLE COURSE MODIFY TODAY VARCHAR(255) DEFAULT 'TODAY';

ALTER TABLE COURSE MODIFY TODAY DATE ;
describe COURSE;

SELECT * FROM STUDENT;
CREATE INDEX STUDENT_INDEX ON STUDENT(NAME);
SHOW INDEX FROM STUDENT;

DROP INDEX STUDENT_INDEX ON STUDENT;

